# The ephemeral game-night server. `gameday up` applies this; `gameday down` destroys it.
# The reserved IP, firewall and data volume are created by bootstrap and only read here,
# so if the reaper force-deletes the server out of band, the next `up` heals cleanly.

data "hcloud_primary_ip" "ipv4" {
  name = "${var.name_prefix}-ipv4"
}

data "hcloud_firewall" "cs2" {
  name = "${var.name_prefix}-fw"
}

data "hcloud_volume" "data" {
  name = "${var.name_prefix}-data"
}

data "hcloud_ssh_key" "admin" {
  name = "${var.name_prefix}-admin"
}

data "hcloud_ssh_key" "admin_macbook" {
  name = "cs-server-admin-mbpm1"
}

locals {
  sides      = [for s in split("v", var.format) : tonumber(s)]
  per_side   = max(local.sides[0], local.sides[1])
  maxplayers = local.per_side * 2 + 3 # + a few caster/spectator slots

  # matchzy mode runs the competitive ruleset (MatchZy manages rounds/econ on
  # top); prophunt runs on the more permissive casual ruleset since PropHunt
  # manages its own round logic; vanilla defaults to competitive for plain play.
  gamealias = {
    matchzy  = "competitive"
    prophunt = "casual"
    vanilla  = "competitive"
  }[var.mode]

  # Only matchzy mode installs MatchZy at all, so this only matters there —
  # autostart_mode 1 = match mode (waits for a real match via !ready /
  # matchzy_loadmatch_url, nothing hardcoded here).
  matchzy_mode_cfg = <<-EOF
    // Generated by terraform/session/main.tf from --mode=matchzy. Do not
    // edit on the server — edit main.tf instead.
    matchzy_autostart_mode 1
  EOF

  # For prophunt/vanilla this is a harmless comment; nothing reads cfg/mode.cfg
  # since MatchZy isn't installed in those modes.
  mode_cfg = var.mode == "matchzy" ? local.matchzy_mode_cfg : "// --mode=${var.mode}: MatchZy isn't installed in this mode, nothing to configure here.\n"

  cloud_init = templatefile("${path.module}/cloud-init.yaml.tftpl", {
    gslt              = var.gslt
    hostname          = var.hostname
    sv_password       = var.sv_password
    rcon_password     = var.rcon_password
    tailscale_authkey = var.tailscale_authkey
    maxplayers        = local.maxplayers
    startmap          = var.map
    gamealias         = local.gamealias
    tv_delay          = var.tv_delay
    mods              = var.mode == "vanilla" ? "0" : "1"
    gamemode          = var.mode
    mode_cfg          = local.mode_cfg
    compose_yml       = file("${path.module}/../../compose/docker-compose.yml")
    server_cfg        = file("${path.module}/../../cfg/server.cfg")
    pre_sh            = file("${path.module}/../../scripts/pre.sh")
    versions_lock     = file("${path.module}/../../addons/versions.lock")
    # admins.json / cssharp-admins.json hold real Steam64 IDs and are git-ignored
    # (see .gitignore); fall back to the committed *.example.json placeholders
    # when a real one isn't present locally.
    matchzy_admins = (
      fileexists("${path.module}/../../cfg/matchzy/admins.json")
      ? file("${path.module}/../../cfg/matchzy/admins.json")
      : file("${path.module}/../../cfg/matchzy/admins.example.json")
    )
    cssharp_admins = (
      fileexists("${path.module}/../../cfg/matchzy/cssharp-admins.json")
      ? file("${path.module}/../../cfg/matchzy/cssharp-admins.json")
      : file("${path.module}/../../cfg/matchzy/cssharp-admins.example.json")
    )
    prophunt_de_dust2   = file("${path.module}/../../cfg/prophunt/de_dust2.txt")
    prophunt_de_nuke    = file("${path.module}/../../cfg/prophunt/de_nuke.txt")
    prophunt_de_inferno = file("${path.module}/../../cfg/prophunt/de_inferno.txt")
    prophunt_de_cache   = file("${path.module}/../../cfg/prophunt/de_cache.txt")
  })
}

resource "hcloud_server" "cs2" {
  name        = "${var.name_prefix}-session"
  server_type = var.server_type
  image       = var.image
  location    = var.location
  ssh_keys    = [data.hcloud_ssh_key.admin.name, data.hcloud_ssh_key.admin_macbook.name]
  user_data   = local.cloud_init

  firewall_ids = [tonumber(data.hcloud_firewall.cs2.id)]

  public_net {
    ipv4_enabled = true
    ipv4         = data.hcloud_primary_ip.ipv4.id
    ipv6_enabled = true
  }

  labels = {
    project = var.name_prefix
    role    = "session"
    format  = var.format
  }
}

resource "hcloud_volume_attachment" "data" {
  volume_id = tonumber(data.hcloud_volume.data.id)
  server_id = tonumber(hcloud_server.cs2.id)
  automount = false # cloud-init mounts it at /opt/cs2/data
}
